package com.panu.competitor.information.pojo.entity;
// Generated Oct 1, 2018 2:56:01 PM by Hibernate Tools 4.3.1


import com.panu.competitor.information.common.ConstantCommon;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LegalIssue generated by hbm2java
 */
@Entity
@Table(name="LegalIssue")
@NamedQueries({
    @NamedQuery(name = "LegalIssue.findLegalIssueListByCompanyId", query = "SELECT c FROM LegalIssue c WHERE c.isDelete=" + ConstantCommon.STATUS_ISDELETE + " AND c.companyId=:companyId")
})
public class LegalIssue  implements java.io.Serializable {


     private int legalIssueId;
     private int companyId;
     private String company;
     private int yearOfLodge;
     private String courtType;
     private boolean isDelete;
     private int createdUserId;
     private Date createdDate;
     private Integer updatedUserId;
     private Date updatedDate;

    public LegalIssue() {
    }
    
    public LegalIssue(LegalIssue legalIssue) {
        this.company = legalIssue.getCompany();
        this.courtType = legalIssue.getCourtType();
        this.yearOfLodge = legalIssue.getYearOfLodge();
    }
	
    public LegalIssue(int legalIssueId, int companyId, String company, int yearOfLodge, String courtType, boolean isDelete, int createdUserId, Date createdDate) {
        this.legalIssueId = legalIssueId;
        this.companyId = companyId;
        this.company = company;
        this.yearOfLodge = yearOfLodge;
        this.courtType = courtType;
        this.isDelete = isDelete;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public LegalIssue(int legalIssueId, int companyId, String company, int yearOfLodge, String courtType, boolean isDelete, int createdUserId, Date createdDate, Integer updatedUserId, Date updatedDate) {
       this.legalIssueId = legalIssueId;
       this.companyId = companyId;
       this.company = company;
       this.yearOfLodge = yearOfLodge;
       this.courtType = courtType;
       this.isDelete = isDelete;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="LegalIssueId", unique=true, nullable=false)
    public int getLegalIssueId() {
        return this.legalIssueId;
    }
    
    public void setLegalIssueId(int legalIssueId) {
        this.legalIssueId = legalIssueId;
    }

    @Column(name="CompanyId", nullable=false)
    public int getCompanyId() {
        return companyId;
    }

    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="Company", nullable=false, length=50)
    public String getCompany() {
        return this.company;
    }

    
    public void setCompany(String company) {
        this.company = company;
    }

    
    @Column(name="YearOfLodge", nullable=false)
    public int getYearOfLodge() {
        return this.yearOfLodge;
    }
    
    public void setYearOfLodge(int yearOfLodge) {
        this.yearOfLodge = yearOfLodge;
    }

    
    @Column(name="CourtType", nullable=false, length=50)
    public String getCourtType() {
        return this.courtType;
    }
    
    public void setCourtType(String courtType) {
        this.courtType = courtType;
    }

    
    @Column(name="IsDelete", nullable=false)
    public boolean isIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(boolean isDelete) {
        this.isDelete = isDelete;
    }

    
    @Column(name="CreatedUserId", nullable=false)
    public int getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(int createdUserId) {
        this.createdUserId = createdUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", nullable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UpdatedUserId")
    public Integer getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Integer updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdatedUserDate", length=23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


