package com.panu.competitor.information.pojo.entity;
// Generated Oct 1, 2018 2:56:01 PM by Hibernate Tools 4.3.1

import com.panu.competitor.information.common.ConstantCommon;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "Location")
@NamedQueries({
    @NamedQuery(name = "Location.getLocation", query = "SELECT t FROM Location t WHERE t.isDelete=" + ConstantCommon.STATUS_ISDELETE),
    @NamedQuery(name = "Location.findLocationById", query = "SELECT t FROM Location t WHERE t.locationId =:locationId AND t.isDelete=" + ConstantCommon.STATUS_ISDELETE)
})
public class Location implements java.io.Serializable {

    private int LocationId;
    private String name;
    private boolean isDelete;
    private int createdUserId;
    private Date createdDate;
    private Integer updatedUserId;
    private Date updatedDate;

    public Location() {
    }

    public Location(int LocationId, String name, boolean isDelete, int createdUserId, Date createdDate) {
        this.LocationId = LocationId;
        this.name = name;
        this.isDelete = isDelete;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }

    public Location(int LocationId, String name, boolean isDelete, int createdUserId, Date createdDate, Integer updatedUserId, Date updatedDate) {
        this.LocationId = LocationId;
        this.name = name;
        this.isDelete = isDelete;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
        this.updatedUserId = updatedUserId;
        this.updatedDate = updatedDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "LocationId", unique = true, nullable = false)
    public int getLocationId() {
        return this.LocationId;
    }

    public void setLocationId(int LocationId) {
        this.LocationId = LocationId;
    }

    @Column(name = "Name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "IsDelete", nullable = false)
    public boolean isIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(boolean isDelete) {
        this.isDelete = isDelete;
    }

    @Column(name = "CreatedUserId", nullable = false)
    public int getCreatedUserId() {
        return this.createdUserId;
    }

    public void setCreatedUserId(int createdUserId) {
        this.createdUserId = createdUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CreatedDate", nullable = false, length = 23)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "UpdatedUserId")
    public Integer getUpdatedUserId() {
        return this.updatedUserId;
    }

    public void setUpdatedUserId(Integer updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UpdatedUserDate", length = 23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

}
