package com.panu.competitor.information.pojo.entity;
// Generated Oct 1, 2018 2:56:01 PM by Hibernate Tools 4.3.1


import com.panu.competitor.information.common.ConstantCommon;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CodeSetup generated by hbm2java
 */
@Entity
@Table(name="CodeSetup")
@NamedQueries({
    @NamedQuery(name = "CodeSetup.findCodeSetupByCodeSetupType", query = "SELECT c FROM CodeSetup c WHERE c.isDelete=" + ConstantCommon.STATUS_ISDELETE + " AND c.codeSetupType=:codeSetupType"),
    @NamedQuery(name = "CodeSetup.findCodeSetupByCodeSetupId", query = "SELECT c FROM CodeSetup c WHERE c.isDelete=" + ConstantCommon.STATUS_ISDELETE + " AND c.codeSetupId=:codeSetupId"),
    @NamedQuery(name = "CodeSetup.findCodeSetupByCodeSetupName", query = "SELECT c FROM CodeSetup c WHERE c.isDelete=" + ConstantCommon.STATUS_ISDELETE + " AND c.codeSetupName=:codeSetupName")
})
public class CodeSetup  implements java.io.Serializable {


     private int codeSetupId;
     private String codeSetupName;
     private String codeSetupType;
     private String description;
     private boolean isDelete;
     private int createdUserId;
     private Date createdDate;
     private Integer updatedUserId;
     private Date updatedDate;

    public CodeSetup() {
    }

	
    public CodeSetup(int codeSetupId, String codeSetupName, boolean isDelete, int createdUserId, Date createdDate) {
        this.codeSetupId = codeSetupId;
        this.codeSetupName = codeSetupName;
        this.isDelete = isDelete;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public CodeSetup(int codeSetupId, String codeSetupName, String codeSetupType, String description, boolean isDelete, int createdUserId, Date createdDate, Integer updatedUserId, Date updatedDate) {
       this.codeSetupId = codeSetupId;
       this.codeSetupName = codeSetupName;
       this.codeSetupType = codeSetupType;
       this.description = description;
       this.isDelete = isDelete;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="CodeSetupId", unique=true, nullable=false)
    public int getCodeSetupId() {
        return this.codeSetupId;
    }
    
    public void setCodeSetupId(int codeSetupId) {
        this.codeSetupId = codeSetupId;
    }
    
    @Column(name="CodeSetupName", nullable=false, length=50)
    public String getCodeSetupName() {
        return this.codeSetupName;
    }
    
    public void setCodeSetupName(String codeSetupName) {
        this.codeSetupName = codeSetupName;
    }

    
    @Column(name="CodeSetupType", length=200)
    public String getCodeSetupType() {
        return this.codeSetupType;
    }
    
    public void setCodeSetupType(String codeSetupType) {
        this.codeSetupType = codeSetupType;
    }

    
    @Column(name="Description", length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="IsDelete", nullable=false)
    public boolean isIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(boolean isDelete) {
        this.isDelete = isDelete;
    }

    
    @Column(name="CreatedUserId", nullable=false)
    public int getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(int createdUserId) {
        this.createdUserId = createdUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", nullable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UpdatedUserId")
    public Integer getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Integer updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdatedDate", length=23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


