package com.panu.competitor.information.pojo.entity;
// Generated Oct 1, 2018 2:56:01 PM by Hibernate Tools 4.3.1

import com.panu.competitor.information.common.ConstantCommon;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "Company")
@NamedQueries({
    @NamedQuery(name = "Company.getCompanies", query = "SELECT t FROM Company t WHERE t.isDelete=" + ConstantCommon.STATUS_ISDELETE),
    @NamedQuery(name = "Company.validateCompany", query = "SELECT t FROM Company t WHERE t.isDelete=" + ConstantCommon.STATUS_ISDELETE + " AND (t.name =:name OR t.companyCode =:companyCode OR t.color =:color)"),
    @NamedQuery(name = "Company.findCompanyByCompanyId", query = "SELECT c FROM Company c WHERE c.isDelete=" + ConstantCommon.STATUS_ISDELETE + " AND c.companyId=:companyId"),
    @NamedQuery(name = "Company.findCompanyByCompanyCode", query = "SELECT c FROM Company c WHERE c.isDelete=" + ConstantCommon.STATUS_ISDELETE + " AND c.companyCode=:companyCode")
})
public class Company implements java.io.Serializable {

    private int companyId;
    private String companyCode;
    private String name;
    private String color;
    private String legalIssueDescription;
    private boolean isDelete;
    private int createdUserId;
    private Date createdDate;
    private Integer updatedUserId;
    private Date updatedDate;

    public Company() {
    }

    public Company(int companyId, String companyCode, String name, String color, boolean isDelete, int createdUserId, Date createdDate) {
        this.companyId = companyId;
        this.companyCode = companyCode;
        this.name = name;
        this.color = color;
        this.isDelete = isDelete;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }

    public Company(int companyId, String companyCode, String name, String color, String legalIssueDescription, boolean isDelete, int createdUserId, Date createdDate, Integer updatedUserId, Date updatedDate) {
        this.companyId = companyId;
        this.companyCode = companyCode;
        this.name = name;
        this.color = color;
        this.legalIssueDescription = legalIssueDescription;
        this.isDelete = isDelete;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
        this.updatedUserId = updatedUserId;
        this.updatedDate = updatedDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CompanyId", unique = true, nullable = false)
    public int getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    @Column(name = "CompanyCode", nullable = false, length = 50)
    public String getCompanyCode() {
        return this.companyCode;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    @Column(name = "Name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "Color", nullable = false, length = 50)
    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }
    
    @Column(name = "LegalIssueDescription", nullable = false, length = 500)
    public String getLegalIssueDescription() {
        return legalIssueDescription;
    }

    public void setLegalIssueDescription(String legalIssueDescription) {
        this.legalIssueDescription = legalIssueDescription;
    }

    @Column(name = "IsDelete", nullable = false)
    public boolean isIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(boolean isDelete) {
        this.isDelete = isDelete;
    }

    @Column(name = "CreatedUserId", nullable = false)
    public int getCreatedUserId() {
        return this.createdUserId;
    }

    public void setCreatedUserId(int createdUserId) {
        this.createdUserId = createdUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CreatedDate", nullable = false, length = 23)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "UpdatedUserId")
    public Integer getUpdatedUserId() {
        return this.updatedUserId;
    }

    public void setUpdatedUserId(Integer updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UpdatedUserDate", length = 23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

}
