package com.panu.competitor.information.pojo.entity;
// Generated Oct 1, 2018 2:56:01 PM by Hibernate Tools 4.3.1

import com.panu.competitor.information.common.ConstantCommon;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompetitorInformation generated by hbm2java
 */
@Entity
@Table(name = "PlantInformation")
@NamedQueries({
    @NamedQuery(name = "CompetitorInformation.getCompetitorInfos", query = "SELECT t FROM PlantInformation t WHERE t.isDelete=" + ConstantCommon.STATUS_ISDELETE),
    @NamedQuery(name = "CompetitorInformation.findComInfoIDByCompanyName", query = "SELECT t FROM PlantInformation t WHERE t.companyName=:companyName AND t.isDelete=" + ConstantCommon.STATUS_ISDELETE),
    @NamedQuery(name = "CompetitorInformation.findCompanyNameByCominfoid", query = "SELECT t FROM PlantInformation t WHERE t.competitorInfoId=:competitorinformationid")
})
public class PlantInformation implements java.io.Serializable {

    private int competitorInfoId;
    private String companyName;
    private Date period;
    private boolean isDelete;
    private int createdUserId;
    private Date createdDate;
    private Integer updatedUserId;
    private Date updatedDate;

    public PlantInformation() {
    }

    public PlantInformation(int competitorInfoId, String companyName, Date period, boolean isDelete, int createdUserId, Date createdDate) {
        this.competitorInfoId = competitorInfoId;
        this.companyName = companyName;
        this.period = period;
        this.isDelete = isDelete;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }

    public PlantInformation(int competitorInfoId, String companyName, Date period, boolean isDelete, int createdUserId, Date createdDate, Integer updatedUserId, Date updatedDate) {
        this.competitorInfoId = competitorInfoId;
        this.companyName = companyName;
        this.period = period;
        this.isDelete = isDelete;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
        this.updatedUserId = updatedUserId;
        this.updatedDate = updatedDate;
    }

    @Id

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CompetitorInfoId", unique = true, nullable = false)
    public int getCompetitorInfoId() {
        return this.competitorInfoId;
    }

    public void setCompetitorInfoId(int competitorInfoId) {
        this.competitorInfoId = competitorInfoId;
    }

    @Column(name = "CompanyName", unique = true, nullable = false, length = 50)
    public String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Period")
    public Date getPeriod() {
        return this.period;
    }

    public void setPeriod(Date period) {
        this.period = period;
    }

    @Column(name = "IsDelete", nullable = false)
    public boolean isIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(boolean isDelete) {
        this.isDelete = isDelete;
    }

    @Column(name = "CreatedUserId", nullable = false)
    public int getCreatedUserId() {
        return this.createdUserId;
    }

    public void setCreatedUserId(int createdUserId) {
        this.createdUserId = createdUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CreatedDate", nullable = false, length = 23)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "UpdatedUserId")
    public Integer getUpdatedUserId() {
        return this.updatedUserId;
    }

    public void setUpdatedUserId(Integer updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UpdatedUserDate", length = 23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

}
