package com.panu.competitor.information.pojo.entity;
// Generated Oct 1, 2018 2:56:01 PM by Hibernate Tools 4.3.1


import com.panu.competitor.information.common.ConstantCommon;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompetitorInformationDetail generated by hbm2java
 */
@Entity
@Table(name="PlantInformationDetail")
@NamedQueries({
     @NamedQuery(name = "PlantInformationDetail.findAllCompetiorInfoDetailByComInfoId", query = "SELECT t FROM PlantInformationDetail t WHERE t.competitorInfoId=:competitorinformationid AND t.isDelete=" + ConstantCommon.STATUS_ISDELETE),
    @NamedQuery(name = "PlantInformationDetail.getCompetitorInfoDetial", query = "SELECT t FROM PlantInformationDetail t WHERE t.isDelete=" + ConstantCommon.STATUS_ISDELETE),
    @NamedQuery(name = "PlantInformationDetail.findAllCompetiorInfoDetailByComInfoDetailId", query = "SELECT t FROM PlantInformationDetail t WHERE t.competitorDetailId=:competitorDetailId AND t.isDelete=" + ConstantCommon.STATUS_ISDELETE)
})
public class PlantInformationDetail  implements java.io.Serializable {


     private int competitorDetailId;
     private int competitorInfoId;
     private int plantId;
     private int location;
     private int noOfPlant;
     private int zone;
     private int noOfTruck;
     private int plantCapacity;
     private int volumePerMonth;
     private char hdbapprove;
     private Date leasePeriodFromDate;
     private Date leasePeriodToDate;
     private String tolDetail;
     private String supportedBy;
     private String capabilities;
     private String longitude;
     private String latitude;
     private boolean isDelete;
     private int createdUserId;
     private Date createdDate;
     private Integer updatedUserId;
     private Date updatedDate;

    public PlantInformationDetail() {
    }

	
    public PlantInformationDetail(int competitorDetailId, int competitorInfoId, int location, int noOfPlant, int zone, int noOfTruck, int volumePerMonth, char hdbapprove, Date leasePeriodFromDate, Date leasePeriodToDate, String supportedBy, String capabilities, boolean isDelete, int createdUserId, Date createdDate) {
        this.competitorDetailId = competitorDetailId;
        this.competitorInfoId = competitorInfoId;
        this.location = location;
        this.noOfPlant = noOfPlant;
        this.zone = zone;
        this.noOfTruck = noOfTruck;
        this.volumePerMonth = volumePerMonth;
        this.hdbapprove = hdbapprove;
        this.leasePeriodFromDate = leasePeriodFromDate;
        this.leasePeriodToDate = leasePeriodToDate;
        this.supportedBy = supportedBy;
        this.capabilities = capabilities;
        this.isDelete = isDelete;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public PlantInformationDetail(int competitorDetailId, int competitorInfoId, int plantId, int location, int noOfPlant, int zone, int noOfTruck, int plantCapacity, int volumePerMonth, char hdbapprove, Date leasePeriodFromDate, Date leasePeriodToDate, String tolDetail, String supportedBy, String capabilities, String longitude, String latitude, boolean isDelete, int createdUserId, Date createdDate, Integer updatedUserId, Date updatedDate) {
       this.competitorDetailId = competitorDetailId;
       this.competitorInfoId = competitorInfoId;
       this.plantId = plantId;
       this.location = location;
       this.noOfPlant = noOfPlant;
       this.zone = zone;
       this.noOfTruck = noOfTruck;
       this.plantCapacity = plantCapacity;
       this.volumePerMonth = volumePerMonth;
       this.hdbapprove = hdbapprove;
       this.leasePeriodFromDate = leasePeriodFromDate;
       this.leasePeriodToDate = leasePeriodToDate;
       this.tolDetail = tolDetail;
       this.supportedBy = supportedBy;
       this.capabilities = capabilities;
       this.longitude = longitude;
       this.latitude = latitude;
       this.isDelete = isDelete;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="CompetitorInfoDetailId", unique=true, nullable=false)
    public int getCompetitorDetailId() {
        return this.competitorDetailId;
    }
    
    public void setCompetitorDetailId(int competitorDetailId) {
        this.competitorDetailId = competitorDetailId;
    }
    
    @Column(name="CompetitorInfoId", nullable=false)
    public int getCompetitorInfoId() {
        return competitorInfoId;
    }

    public void setCompetitorInfoId(int competitorInfoId) {
        this.competitorInfoId = competitorInfoId;
    }
    
    @Column(name="Location", nullable=false)
    public int getLocation() {
        return this.location;
    }
    
    public void setLocation(int location) {
        this.location = location;
    }

    
    @Column(name="NoOfPlant", nullable=false)
    public int getNoOfPlant() {
        return this.noOfPlant;
    }
    
    public void setNoOfPlant(int noOfPlant) {
        this.noOfPlant = noOfPlant;
    }

    
    @Column(name="Zone")
    public int getZone() {
        return zone;
    }
    
    public void setZone(int zone) {
        this.zone = zone;
    }

    
    @Column(name="NoOfTruck")
    public int getNoOfTruck() {
        return noOfTruck;
    }
    
    public void setNoOfTruck(int noOfTruck) {
        this.noOfTruck = noOfTruck;
    }

    
    @Column(name="PlantCapacity")
    public int getPlantCapacity() {
        return plantCapacity;
    }
    
    public void setPlantCapacity(int plantCapacity) {
        this.plantCapacity = plantCapacity;
    }

    
    @Column(name="VolumePerMonth")
    public int getVolumePerMonth() {
        return volumePerMonth;
    }
    
    public void setVolumePerMonth(int volumePerMonth) {
        this.volumePerMonth = volumePerMonth;
    }

    
    @Column(name="HDBApprove", length=1)
    public char getHdbapprove() {
        return this.hdbapprove;
    }
    
    public void setHdbapprove(char hdbapprove) {
        this.hdbapprove = hdbapprove;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LeasePeriodFromDate", length=10)
    public Date getLeasePeriodFromDate() {
        return this.leasePeriodFromDate;
    }
    
    public void setLeasePeriodFromDate(Date leasePeriodFromDate) {
        this.leasePeriodFromDate = leasePeriodFromDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LeasePeriodToDate", length=10)
    public Date getLeasePeriodToDate() {
        return this.leasePeriodToDate;
    }
    
    public void setLeasePeriodToDate(Date leasePeriodToDate) {
        this.leasePeriodToDate = leasePeriodToDate;
    }
    
    @Column(name="TolDetail",length=100)
    public String getTolDetail() {
        return tolDetail;
    }

    public void setTolDetail(String tolDetail) {
        this.tolDetail = tolDetail;
    }
    
    
    @Column(name="SupportedBy",length=50)
    public String getSupportedBy() {
        return this.supportedBy;
    }
    
    public void setSupportedBy(String supportedBy) {
        this.supportedBy = supportedBy;
    }

    
    @Column(name="Capabilities", length=7)
    public String getCapabilities() {
        return this.capabilities;
    }
    
    public void setCapabilities(String capabilities) {
        this.capabilities = capabilities;
    }

    
    @Column(name="Longitute")
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="Latitute")
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    @Column(name="IsDelete", nullable=false)
    public boolean isIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(boolean isDelete) {
        this.isDelete = isDelete;
    }

    
    @Column(name="CreatedUserId", nullable=false)
    public int getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(int createdUserId) {
        this.createdUserId = createdUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", nullable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UpdatedUserId")
    public Integer getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Integer updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdatedUserDate", length=23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    @Column(name="PlantId")
    public int getPlantId() {
        return plantId;
    }

    public void setPlantId(int plantId) {
        this.plantId = plantId;
    }
    
}


