package com.panu.competitor.information.pojo.entity;
// Generated Oct 1, 2018 2:56:01 PM by Hibernate Tools 4.3.1

import com.panu.competitor.information.common.ConstantCommon;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "Role")
@NamedQueries({
    @NamedQuery(name = "Role.findRoleByRole", query = "SELECT c FROM Role c WHERE c.isDelete=" + ConstantCommon.STATUS_ISDELETE + " AND c.roleId=:roleId"),
    @NamedQuery(name = "Plant.getRoles", query = "SELECT t FROM Role t WHERE t.isDelete=" + ConstantCommon.STATUS_ISDELETE)
})
public class Role implements java.io.Serializable {

    private int roleId;
    private String roleName;
    private boolean isDelete;
    private int createdUserId;
    private Date createdDate;
    private Integer updatedUserId;
    private Date updatedUserDate;

    public Role() {
    }

    public Role(int roleId, String roleName, boolean isDelete, int createdUserId, Date createdDate) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.isDelete = isDelete;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }

    public Role(int roleId, String roleName, boolean isDelete, int createdUserId, Date createdDate, Integer updatedUserId, Date updatedUserDate) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.isDelete = isDelete;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
        this.updatedUserId = updatedUserId;
        this.updatedUserDate = updatedUserDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "RoleId", unique = true, nullable = false)
    public int getRoleId() {
        return this.roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    @Column(name = "RoleName", nullable = false, length = 50)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name = "IsDelete", nullable = false)
    public boolean isIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(boolean isDelete) {
        this.isDelete = isDelete;
    }

    @Column(name = "CreatedUserId", nullable = false)
    public int getCreatedUserId() {
        return this.createdUserId;
    }

    public void setCreatedUserId(int createdUserId) {
        this.createdUserId = createdUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CreatedDate", nullable = false, length = 23)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "UpdatedUserId")
    public Integer getUpdatedUserId() {
        return this.updatedUserId;
    }

    public void setUpdatedUserId(Integer updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UpdatedUserDate", length = 23)
    public Date getUpdatedUserDate() {
        return this.updatedUserDate;
    }

    public void setUpdatedUserDate(Date updatedUserDate) {
        this.updatedUserDate = updatedUserDate;
    }

}
